language: android

notifications:
  email:
    recipients:
      - momo-du_78@hotmail.fr
      - camleuregans@gmail.com
      - cle.burg@hotmail.fr
    on_success: never
    on_failure: never

# JDK
jdk:
  - oraclejdk8
  - oraclejdk7

# Script pour utiliser un des JDK
script:
- jdk_switcher use oraclejdk8
- # do stuff with Java 8
- jdk_switcher use oraclejdk7
- # do stuff with Java 7

android:
  components:
    # The latest revision of Android SDK Tools
     - platform-tools
     - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-18
    - sys-img-x86-android-17

    # Repositories for Gradle and Maven
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}


# Gradlew
before_install:
 - chmod +x ./gradlew
 
script:
  - ./gradlew clean build
