package grp3.projet.miage.paris10.fr.m1c20152016_planinteractifbu.bibliotheque.salle;

public enum Service {
    HALL,
    ACCES,
    ENTREE,
    SORTIE,
    CAFETERIA,
    WC,
    ESPACE_PRESSE,
    SERVICE_DE_REPROGRAPHIE,
    ESCALIER,
    ESPACE_BANDES_DESSINEES,
    ATELIER_DOCUMENTAIRE,
    VIDEOTHEQUE,
    PRET_RETOUR,
    PRET_A_DOMICILE,
    PEB_PEE,
    COMMUNICATION_ET_PRET_EN_MAGASIN,
    SALLE_INFORMATIQUE_ADAPTEE,
    REVUES_DE_LETTRES,
    SECRETARIAT,
    OBJETS_TROUVES,
    DIRECTION,
    ESPACE_DE_TRAVAIL,
    ESPACE_DE_TRAVAIL_EN_GROUPE,
    COPIEURS_IMPRIMANTES,

}
