package grp3.projet.miage.paris10.fr.m1c20152016_planinteractifbu.bibliotheque.discipline;

public enum EnumSousDiscipline {
    ADMINISTRATION_PUBLIQUE,
    DROIT,
    SCIENCES_POLITIQUES,
    ARCHEOLOGIE,
    ARTS_DU_SPECTACLE,
    GEOGRAPHIE,
    HISTOIRE,
    HISTOIRE_DE_L_ART,
    PHILOSOPHIE,
    RELIGION,
    ANTHROPOLOGIE,
    ETHNOLOGIE,
    PSYCHOLOGIE,
    SCIENCES_DE_L_EDUCATION,
    SCIENCES_ET_MEDECINE,
    SOCIOLOGIE,
    STAPS_SPORT,
    ECONOMIE,
    INFORMATIQUE,
    MATHEMATIQUES,
    LANGUES,
    LETTRES,
    SCIENCES_DU_LANGAGE
}
